AWSTemplateFormatVersion: "2010-09-09"
Description: "Create a VGW with a VPN Connection.  Add a route in the VPC RouteTable for the remote CIDR and associate a local VPC with the VGW"
Parameters:
    VGWASN:
      Type: Number
      #ASN 65000 has issues with this setup due to CGW creates ASN by default as 65000, and that conflicts with TGW
      Default: 65001
      MinValue: 65001
      MaxValue: 65534
    CGWASN:
      Type: Number
      Default: 65000
      MinValue: 64512
      MaxValue: 65534
    CGWIPAddr:
      Description: Should be dummy IP to start
      Type: String
      Default: 1.1.1.1
    CGWName:
      Type: String
    VGWName:
      Type: String
    VPCId:
      Type: AWS::EC2::VPC::Id
    SubnetId:
      Description: Subnet ID for where this VPN Gateway will reside
      Type: AWS::EC2::Subnet::Id
    TunnelCidr:
      Type: String
      Default: "169.254.6.0/30"
    # should use something like SSM Pareameter Store or AWS SecretManager but this is a demo
    PreSharedKey:
      Type: String
      NoEcho: True
      MinLength: 8
      MaxLength: 64
      AllowedPattern: "^[a-z][a-zA-Z._0-9]+$"
    RemoteCIDR:
      Type: String
      Description: "must be a valid IP CIDR range of the form x.x.x.x/x."
      AllowedPattern: "(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})\\.(\\d{1,3})/(\\d{1,2})"
      ConstraintDescription: "must be a valid IP CIDR range of the form x.x.x.x/x."
    VPCRouteTableID:
      Type: String
      AllowedPattern: "^rtb-[a-z0-9]+"
      MaxLength: 22
Resources:
    EC2VPNConnection:
        Type: "AWS::EC2::VPNConnection"
        Properties:
            Type: "ipsec.1"
            StaticRoutesOnly: True
            CustomerGatewayId: !Ref EC2CustomerGateway
            VpnGatewayId: !Ref EC2VPNGateway
            VpnTunnelOptionsSpecifications: 
              -  
                PreSharedKey: !Ref PreSharedKey
                TunnelInsideCidr: !Ref TunnelCidr
            Tags: 
              - 
                Key: "Name"
                Value: !Sub ${VGWName}-VPN-to-${CGWName}
    EC2CustomerGateway:
        Type: "AWS::EC2::CustomerGateway"
        Properties:
            BgpAsn: !Ref CGWASN
            IpAddress: !Ref CGWIPAddr
            Type: "ipsec.1"
            Tags: 
              - 
                Key: "Name"
                Value: !Ref CGWName
    EC2Route:
        Type: "AWS::EC2::Route"
        DependsOn: EC2VPNHubAttachment
        Properties:
            DestinationCidrBlock: !Ref RemoteCIDR
            RouteTableId: !Ref VPCRouteTableID
            GatewayId: !Ref EC2VPNGateway
    EC2VPNGateway:
        Type: "AWS::EC2::VPNGateway"
        Properties:
            AmazonSideAsn: !Ref VGWASN
            Type: "ipsec.1"
            Tags: 
              - 
                Key: "Name"
                Value: "hub-vgw"
    EC2VPNHubAttachment:
          Type: AWS::EC2::VPCGatewayAttachment
          Properties: 
            VpcId: !Ref VPCId
            VpnGatewayId: !Ref EC2VPNGateway

